name: thử nghiệm đọc file READMEREADME
on:
  push: 
    branches: ["main'"]

jobs:
  thuc_hanh_doc_file:
    run on: ubuntu-latesr

  steps: 
  - name: Bước 1 - Xin chào
    run: echo "HELLO HUTECH!"
  
  - name: Bước 2 - Tải code
   uses: actions/checkout@v6 
  
  - name: Bước 3 - Đọc file
    run: cat README.md 
